Repository ElvinPero/PriceTemplate, pull requests merged in 2022-10, with the labels that each got.

#17 dark mode
  app.css
  icons8-sun-50.png
  index.html
  moon-and-stars-svgrepo-com.svg
Labels: hacktoberfest, hacktoberfest-accepted

#12 Better layout on mobile breakpoint
  app.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#18 btn to top added without conflicts
  app.css
  index.html
Labels: hacktoberfest-accepted

#19 Added the preloader on the startup of the website
  app.css
  index.html
Labels: hacktoberfest-accepted

#22 added the nav bar
  app.css
  index.html
Labels: hacktoberfest-accepted

#32 website icon added
  app.css
  de7b343c17564851bc467ef560cfa8ab.png
  index.html
Labels: hacktoberfest-accepted

#29 Added code in app.css for styling of buttons(continuation to issue #20)
  app.css
Labels: enhancement, hacktoberfest-accepted

#33 fixed darkmode button and navbar sticky
  index.html
Labels: hacktoberfest-accepted

#43 Removed unnecessary css + Organised Files into folders.
  assets/de7b343c17564851bc467ef560cfa8ab.png
  assets/icons/.DS_Store
  assets/icons/icon1.png
  assets/icons/icon2.png
  assets/icons/icon3.png
  assets/icons8-sun-50.png
  assets/moon-and-stars-svgrepo-com.svg
  css/loader.css
  css/main.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#47 Dynamic CSS
  README.md
  css/app.css
  css/main.css
  index.html
  script.js
  styles/style1.css
  styles/style2.css
  styles/style3.css
Labels: hacktoberfest-accepted

#49 Fixes #35: Add templates of design1 to index
  .gitignore
  app.css
  de7b343c17564851bc467ef560cfa8ab.png
  index.html
Labels: hacktoberfest-accepted

#57 Added Dark Mode Perfectly in the main page.
  css/main.css
  index.html
  script.js
Labels: hacktoberfest, feature

#78 Issue #76 solve, custom scrollbar added
  css/main.css
Labels: hacktoberfest-accepted

#85 Feature darkmode
  assets/logo.png
  assets/moon-and-stars-svgrepo-com.svg
  css/loader.css
  css/main.css
  css/togglebtn.css
  index.html
  js/haptics.js
  js/togglebtn.js
  script.js
  styles/style1.css
  styles/style2.css
  styles/style3.css
Labels: hacktoberfest-accepted

#90 Autogenerated PR template added
  .github/pull_request_template.md
Labels: hacktoberfest-accepted

#97 Solved issue no. #87
  About-Us-image.jpg
  css/About-Us.css
  index.html
Labels: hacktoberfest-accepted

#110 issue with about-us button solved
  css/About-Us.css
  index.html
  styles/style1.css
  styles/style2.css
  styles/style3.css
Labels: hacktoberfest-accepted

#123 Bug Fixes
  contact.html
  index.html
Labels: hacktoberfest-accepted

#118 Preloader/udit
  contact.html
  css/preloader.css
  index.html
  js/preloader.js
  pricetable_design_1.html
Labels: hacktoberfest-accepted

#129 Update Contact Page (links work, dark mode, content, theme{background with some animations simple design})
  contact.html
  css/contact-us.css
  css/togglebtn.css
Labels: hacktoberfest-accepted

#132 ADDED THE FAVICON TO THE WEBPAGE
  favicon.ico
  index.html
Labels: enhancement
